### ISSUE TITLE
Auto Leveling G29 / {Palpeur}

### ISSUE THREAD

**Issue by ngraziano** [ubitux/cura-dagoma#5]
Pour moi la commande d'auto leveling G29 manque dans le machine_start_gcode.

Dans Cura-by-Dagoma-Easy200 la ligne ";{palpeur}" du GCODE de début est remplacé par G29 si la case "Utilisation du palpeur"  est coché. Le point virgule est remplacé avec.

C'est fait dans Cura/util/profile.py ligne 1219 :
```python
	"""ERIC"""
	if tag == 'palpeur':
		return getPalpeurGCode()
```

Peut on prévoir de l'activer tout le temps en ajoutant un cas particulier dans le code de conversion definition.py ?

**Comment by ubitux** [comment]
Ah le point virgule saute vraiment avec ? Mince, j'avais pas tilté ça. Je regarde ce soir. Je pensais que c'était un relicat de la discovery.

**Comment by BuBuaBu** [comment]
Non, le ';' ne saute pas. Mais {palpeur} est remplacer par 2 ou 3 lignes dont la première est un commentaire, et une autre le G29.

Perso, je n'utilise pas le palpeur mais je n'ai trouvé aucun moyen de paramétrer depuis cura.

**Comment by ngraziano** [comment]
Par exemple ça donne ça en début de fichier gcode quand on coche palpeur :
```
;Gcode by Cura-by-dagoma for DiscoEASY200 V1.0.2
G90   ;absolute positioning
........
M104 S215
;Activation palpeur
;bloc palpeur
G29
M107 ;start with the fan off
.....
```

Quand on coche pas le palpeur :
```
;Gcode by Cura-by-dagoma for DiscoEASY200 V1.0.2
G90   ;absolute positioning
........
M104 S215
;Activation palpeur
;bloc palpeur
;No Palpeur
M107 ;start with the fan off
.......
```

Après dans Cura 2.4 je n'ai pas trouvé non plus de paramètre lié au palpeur ni à auto leveling, je pense que c'est un ajout de dagoma.  
Perso je le mets par habitude  et je pensais que c'était vraiment nécessaire (je suis encore débutant en impression). Et j'ai été surpris de ne pas voir l'imprimante tester les 4 coins du plateau la première fois que j'ai utilisé Cura 2.4.
Mais sinon je peux l'ajouter à la main si c'est optionnel.

**Comment by ubitux** [comment]
Est-ce que le palpeur est activé par défaut sur la discoeasy ? On est d'accord que dans le cas de la discovery si j'ai bien compris c'était un addon physique à plug ?

**Comment by ngraziano** [comment]
Pour la discoeasy, oui le palpeur est activé par défaut. Pour la discovery je ne connais pas.

**Comment by ubitux** [comment]
J'ai mis le `G29` mais pas testé. J'espère que c'est good :)

**Comment by ngraziano** [comment]
Merci.

**Comment by arthurlutz** [comment]
Est-ce que on peut utilise G29.2 ?
